# Place the site into maintenance mode
# Log to /mnt/shared-storage/logs
deploy:
  rancher-drone-execute:
    image: eastest/drone-rancher-execute
    url: $$RANCHER_URL
    access_key: $$RANCHER_ACCESS_KEY
    secret_key: $$RANCHER_SECRET_KEY
    service: $$SERVICE_NAME
    cmd: "drush vset site_offline TRUE --root=/var/application/www >> /mnt/shared-storage/logs/deploy-log.log 2>&1"
    exec_timeout: 600


deploy:
  rancher-drone-execute:
    image: eastest/drone-rancher-execute
    url: $$RANCHER_URL
    access_key: $$RANCHER_ACCESS_KEY
    secret_key: $$RANCHER_SECRET_KEY
    service: $$SERVICE_NAME
    cmd: "TT=testsite5 && TEMPSITENAME=`drush vget site_name --root=/var/application/www` && AA=`echo $TEMPSITENAME| sed 's/ //g'|cut -d\\' -f2`  &&  drush sql-dump --result-file=/mnt/shared-storage/backups/`echo $TT`_testdeploy_`date +%Y-%m-%d_%H:%M:%S`.sql --root=/var/application/www > /mnt/shared-storage/logs/complextest.log 2>&1"
    exec_timeout: 300

# Deploy the updated code base to the Rancher environment
# Perform a pre deploy db backup
# Log to /mnt/shared-storage/logs
deploy:
  rancher-drone-execute:
    image: eastest/drone-rancher-execute
    url: $$RANCHER_URL
    access_key: $$RANCHER_ACCESS_KEY
    secret_key: $$RANCHER_SECRET_KEY
    service: $$SERVICE_NAME
    cmd: "TEMPSITENAME=`drush vget site_name --root=/var/application/www`; TT=`echo $TEMPSITENAME| sed 's/ //g'|cut -d\\' -f2`; drush sql-dump --result-file=/mnt/shared-storage/backups/`echo $TT`_predeploy_`date +%Y-%m-%d_%H:%M:%S`.sql --root=/var/application/www >> /mnt/shared-storage/logs/deploy-log.log 2>&1"
    exec_timeout: 600

# Deploy the updated code base to the Rancher environment
# permform a rolling restart of containers which will automatically
# pull down the code.
deploy:
  rancher:
    url: $$RANCHER_URL
    access_key: $$RANCHER_ACCESS_KEY
    secret_key: $$RANCHER_SECRET_KEY
    service: $$SERVICE_NAME
    docker_image: $$SERVICE_CONTAINER
    confirm: true
    timeout: 300

# Perform a drush updb on the site
# Log to /mnt/shared-storage/logs
deploy:
  rancher-drone-execute:
    image: eastest/drone-rancher-execute
    url: $$RANCHER_URL
    access_key: $$RANCHER_ACCESS_KEY
    secret_key: $$RANCHER_SECRET_KEY
    service: $$SERVICE_NAME
    cmd: "drush updb -y --root=/var/application/www >> /mnt/shared-storage/logs/deploy-log.log 2>&1"
    exec_timeout: 600

# Perform a cache clear on the site
# # Log to /mnt/shared-storage/logs
deploy:
  rancher-drone-execute:
    image: eastest/drone-rancher-execute
    url: $$RANCHER_URL
    access_key: $$RANCHER_ACCESS_KEY
    secret_key: $$RANCHER_SECRET_KEY
    service: $$SERVICE_NAME
    cmd: "drush cc all -y --root=/var/application/www >> /mnt/shared-storage/logs/deploy-log.log 2>&1"
    exec_timeout: 600

# Perform a post deploy db backup
# Log to /mnt/shared-storage/logs
deploy:
  rancher-drone-execute:
    image: eastest/drone-rancher-execute
    url: $$RANCHER_URL
    access_key: $$RANCHER_ACCESS_KEY
    secret_key: $$RANCHER_SECRET_KEY
    service: $$SERVICE_NAME
    cmd: "drush sql-dump --result-file=/mnt/shared-storage/backups/postdeploy_`date +%Y-%m-%d_%H:%M:%S`.sql --root=/var/application/www >> /mnt/shared-storage/logs/deploy-log.log 2>&1"
    exec_timeout: 600


# Perform a cache clear on the site
# Take the site out of maintenance mode
# Log to /mnt/shared-storage/logs
deploy:
  rancher-drone-execute:
    image: eastest/drone-rancher-execute
    url: $$RANCHER_URL
    access_key: $$RANCHER_ACCESS_KEY
    secret_key: $$RANCHER_SECRET_KEY
    service: $$SERVICE_NAME
    cmd: "drush vset site_offline FALSE --root=/var/application/www >> /mnt/shared-storage/logs/deploy-log.log 2>&1"
    exec_timeout: 600
