deploy:
  rancher:
    url: $$RANCHER_URL
    access_key: $$RANCHER_ACCESS_KEY
    secret_key: $$RANCHER_SECRET_KEY
    service: $$SERVICE_NAME
    docker_image: $$SERVICE_CONTAINER
    confirm: true
    timeout: 300
